#!/usr/bin/env ansible-playbook

---
- name: play 'testlink.ansible.role/setup.yml'
  hosts: all
  become: yes

  vars_files:
    - vars/main.yml

  vars:
    modify_hostname: true

  pre_tasks:
    - name: rename hostname
      hostname: name={{ hostname }}
      when: modify_hostname == true

  roles:
    #- chusiang.switch-apt-mirror
    #- chusiang.vim-and-vi-mode
    - williamyeh.nginx
    - chusiang.php7
    - geerlingguy.mysql

  tasks:
    - name: include main task
      include: tasks/main.yml

    - name: include check task
      include: tasks/check.yml
        
  handlers:
    - include: handlers/main.yml

# vim:ft=ansible:
