#!/usr/bin/env ansible-playbook

---
- name: play 'testlink.ansible.role/setup.yml'
  hosts: all
  become: true

  vars_files:
    - defaults/main.yml

  pre_tasks:
    - name: Add MySQL repository before roles
      include_tasks: tasks/add_mysql_repo.yml
      when: ansible_distribution == 'Debian'

  roles:
    # Only for development.
    #- chusiang.switch-apt-mirror
    #- chusiang.vim-and-vi-mode

    - williamyeh.nginx
    - chusiang.php7
    - {
        role: geerlingguy.mysql,
        mysql_packages: ['mysql-server', 'mysql-client', 'python-mysqldb'],
        when: "ansible_distribution == 'Debian'"
      }
    - {
        role: geerlingguy.mysql,
        mysql_packages: ['mysql-server-5.6', 'mysql-client-5.6', 'python-mysqldb'],
        when: "ansible_distribution == 'Ubuntu'"
      }

  tasks:
    - name: Include main task
      import_tasks: tasks/main.yml

  handlers:
    - name: Include handler task
      import_tasks: handlers/main.yml

# vim: ft=ansible :
