---
# tasks file for testlink

- debug: msg='==> setup TestLink'

# Get TestLink.
- name: download testlink tarball
  get_url: >
    url='http://downloads.sourceforge.net/project/testlink/TestLink%201.9/TestLink%201.9.15/testlink-1.9.15.tar.gz'
    dest=/tmp/testlink-1.9.15.tar.gz
    checksum='md5:d5b9a3e93cdfd9c8d9daed7fa4257409'

- name: unarchive testlink tarball
  unarchive: src=/tmp/testlink-1.9.15.tar.gz dest=/tmp copy=no

# Create TestLink workspace
- name: check `/tmp/testlink-1.9.15` path
  stat: path=/tmp/testlink-1.9.15
  register: unarchive_testlink_stat

- name: move testlink directory into nginx 
  become: yes
  command: mv /tmp/testlink-1.9.15 {{ nginx_testlink_path }}
  #command: mv /tmp/testlink-1.9.15 /usr/share/nginx/testlink
  when: unarchive_testlink_stat.stat.exists
  ignore_errors: yes

# Read/write permissions
- name: create testlink directory
  file: >
    path='{{ item }}' state=directory
    owner=www-data group=www-data mode=0775
  with_items:
    - '{{ testlink_var_path }}'
    - '{{ testlink_var_path }}/logs/'
    - '{{ testlink_var_path }}/upload_area/' 

- name: chmod something
  become: yes
  shell: chmod -R g+w {{ item }}
  with_items:
    - '/usr/share/nginx/testlink'

- name: chown something
  become: yes
  shell: chown -R www-data:www-data {{ item }}
  with_items:
    - '/usr/share/nginx/testlink'

# Database
- name: create testlink database
  mysql_db: >
    name={{ testlink_db_name }} state=present
    encoding=utf8 collation=utf8_general_ci

- name: create testlink table and data
  mysql_db: >
    name={{ testlink_db_name }} state=import
    target={{ item }}
  with_items:
    - '{{ nginx_testlink_path }}/install/sql/mysql/testlink_create_tables.sql'
    - '{{ nginx_testlink_path }}/install/sql/mysql/testlink_create_default_data.sql'
  ignore_errors: yes

- name: create user for testlink database
  mysql_user: >
    name={{ testlink_db_user }} host=localhost state=present
    password=cUv4UK6ardC6cMGL priv={{ testlink_db_name }}.*:ALL
  ignore_errors: yes

